Repository dictation-toolbox/Caster, pull requests merged in 2018-12, with the labels that each got.

#334 Add a Go module
  caster/doc/readthedocs/CCR languages Quick Reference.md
  caster/lib/ccr/__init__.py
  caster/lib/ccr/go/go.py
Labels: Grammar, New Feature

#335 Add fman support
  caster/apps/fman.py
  caster/doc/readthedocs/Application Commands Quick Reference.md
  caster/lib/settings.py
Labels: Grammar, New Feature

#333 Update Atom Command Rules
  caster/apps/__init__.py
  caster/apps/atom.py
  caster/lib/ccr/__init__.py
  caster/lib/settings.py
Labels: Grammar, Refactor

#350 Small sublime update
  caster/apps/rstudio.py
  caster/apps/sublime.py
  caster/doc/readthedocs/Application Commands Quick Reference.md
Labels: Enhancement, Grammar

#353 Change lgl operators to element wise in r.py
  caster/lib/ccr/r/r.py
Labels: Enhancement

#351 File dialogue rule
  caster/apps/file_dialogue.py
  caster/doc/readthedocs/Application Commands Quick Reference.md
  caster/lib/settings.py
Labels: Grammar, New Feature

#359 Update installation instructions
  caster/bin/inno/dependencies/Pip Install Dependencies.bat
  caster/bin/inno/dependencies/Pip Uninstall Dependencies.bat
  caster/doc/Installation.md
Labels: Documentation, Enhancement, Installation

#364 UI path finding bug fix
  caster/asynch/hmc/h_launch.py
  caster/asynch/hmc/hmc_ask_directory.py
  caster/asynch/hmc/hmc_confirm.py
  caster/asynch/hmc/hmc_recording.py
  caster/asynch/hmc/homunculus.py
  caster/asynch/mouse/grids.py
  caster/asynch/mouse/legion.py
  caster/asynch/settingswindow.py
  caster/lib/settings.py
  caster/lib/utilities.py
Labels: Bug
