Repository dictation-toolbox/Caster, pull requests merged in 2018-04, with the labels that each got.

#216 Add Import Tolerance
  caster/apps/__init__.py
  caster/lib/ccr/__init__.py
  caster/user/filters/__init__.py
  caster/user/rules/__init__.py
Labels: Enhancement, Testing Required, [WIP]

#230 Add more text spacing formats e.g. hello.world, hello/world & hello\world
  CasterQuickReference0.5.4.pdf
  CasterQuickReference0.5.5.pdf
  caster/doc/caster_quick_reference.docx
  caster/lib/ccr/core/nav.py
  caster/lib/textformat.py
Labels: Complete, Enhancement

#229 Enclose text into quotes,parens,etc.
  caster/lib/ccr/core/nav.py
  caster/lib/context.py
  caster/lib/textformat.py
Labels: Enhancement, [WIP]

#231 add navigation to explorer
  caster/apps/explorer.py
Labels: Documentation, Enhancement
