Repository dictation-toolbox/Caster, pull requests merged in 2018-09, with the labels that each got.

#227 Add an initial draft of R, Matlab CCR grammars
  caster/lib/ccr/matlab/__init__.py
  caster/lib/ccr/matlab/matlab.py
  caster/lib/ccr/r/__init__.py
  caster/lib/ccr/r/r.py
Labels: New Grammar, Waiting for User Reply

#249 Update R functionality
  caster/lib/ccr/__init__.py
  caster/lib/ccr/matlab/matlab.py
  caster/lib/ccr/r/r.py
Labels: Enhancement

#250 Add [] to the hug function
  caster/lib/ccr/core/nav.py
Labels: Enhancement

#251 Slight quick reference update update
  CasterQuickReference0.5.5.pdf
  CasterQuickReference0.5.6.pdf
  caster/doc/caster_quick_reference.docx
Labels: Documentation

#253 Make the SQL module output in caps.
  caster/lib/ccr/html/html.py
  caster/lib/ccr/sql/sql.py
Labels: Complete, Enhancement

#257 Enhancements to Java, Javascript, Python, Dart CCR language files and Jetbrains.
  caster/apps/jetbrains.py
  caster/lib/ccr/__init__.py
  caster/lib/ccr/dart/__init__.py
  caster/lib/ccr/dart/dart.py
  caster/lib/ccr/java/java.py
  caster/lib/ccr/javascript/javascript.py
  caster/lib/ccr/python/python.py
Labels: Enhancement, New Feature

#252 Reimplementation methods to find DNS path via the registry
  caster/bin/inno/dependencies/pip.bat
  caster/lib/settings.py
Labels: Complete, Enhancement, Installation, Testing Required

#259 Applications quick reference
  caster/doc/readthedocs/Application commands quick reference.md
Labels: Documentation, New Feature
