Repository dictation-toolbox/Caster, pull requests merged in 2018-03, with the labels that each got.

#207 Prolog and vhdl rules
  caster/lib/ccr/vhdl/vhdl.py
  caster/lib/ccr/vhdl/vhdl_strings.py
Labels: New Feature

#212 Updated Atom Commands
  caster/apps/atom.py
Labels: Enhancement

#213 Support for Gitter App
  caster/apps/gitter.py
  caster/lib/settings.py
Labels: New Grammar, [WIP]

#208 Unicode fixes
  caster/lib/dfplus/merge/gfilter.py
  caster/lib/navigation.py
  caster/lib/settings.py
  caster/lib/utilities.py
Labels: Enhancement
