Repository dictation-toolbox/Caster, pull requests merged in 2019-04, with the labels that each got.

#432 Method to clear Status Window
  CasterQuickReference.pdf
  castervoice/apps/dragon.py
  castervoice/doc/CasterQuickReference.tex
  castervoice/lib/utilities.py
Labels: Complete, NatLink, New Feature

#437 Couple of new sublime rules
  castervoice/apps/sublime.py
  castervoice/doc/readthedocs/Application_Commands_Quick_Reference.md
Labels: Enhancement, Grammar

#438 By default print_rdescripts and dev_commands are set to true
  castervoice/lib/settings.py
Labels: Caster Core Spec, Documentation

#445 add Adobe Acrobat command module
  castervoice/apps/adobe_acrobat.py
  castervoice/doc/readthedocs/Application_Commands_Quick_Reference.md
Labels: Grammar, New Feature

#448 Speed up Text execution
  castervoice/lib/actions.py
Labels: Complete, Dragonfly, Enhancement

#450 Renamed development to VoiceDevCommands
  castervoice/doc/readthedocs/CCR_languages_Quick_Reference.md
  castervoice/lib/ccr/__init__.py
  castervoice/lib/ccr/voice_dev_commands/__init__.py
  castervoice/lib/ccr/voice_dev_commands/voice_dev_commands.py
Labels: Refactor

#436 VScode
  castervoice/apps/vscode.py
  castervoice/doc/readthedocs/Application_Commands_Quick_Reference.md
Labels: Enhancement, Grammar

#452 Make gitbash rule CCR
  castervoice/apps/gitbash.py
Labels: Enhancement, Grammar

#453 Outlook: improve reply commands and empty search bar command
  castervoice/apps/outlook.py
Labels: Enhancement, Grammar

#454 Enable and disable CCR
  _caster.py
  castervoice/lib/dfplus/merge/ccrmerger.py
Labels: Caster Core Spec, New Feature

#461 Simplified and updated install instructions
  castervoice/doc/Installation.md
Labels: Documentation, Installation

#462 Function to determine caster install type
  _caster.py
Labels: Installation

#465 Clipboard content from ASCII to Unicode
  castervoice/lib/context.py
Labels: Caster Core Spec

#470 Copied configdebug.txt to user space
  castervoice/lib/dev/dev.py
Labels: Caster, Refactor

#469 Copied bringme.toml.defaults to user space as bringme.toml with yapf
  castervoice/lib/ccr/recording/bringme.py
Labels: Bug, Caster, Installation

#467 Deduplicate text copy
  castervoice/lib/navigation.py
Labels: Caster, Refactor

#473 add Windows Explorer main window navigation commands
  castervoice/apps/explorer.py
Labels: Enhancement, Grammar
