Repository dictation-toolbox/Caster, pull requests merged in 2019-05, with the labels that each got.

#472 Sikuli Fix #463,#468
  _caster.py
  castervoice/asynch/sikuli/sikuli.py
Labels: Bug, Sikulix

#478 Fixed error in section "Template-based navigation"
  castervoice/doc/CasterQuickReference.tex
Labels: Documentation

#481 move some commands in nav.py to CCR from non-CCR
  castervoice/lib/ccr/core/nav.py
Labels: Caster Core Spec, Refactor

#489 fix periodic terminator comment
  castervoice/lib/ccr/core/nav.py
Labels: Complete, Documentation

#451 Redesign rdescripts
  castervoice/apps/chrome.py
  castervoice/lib/ccr/core/nav.py
  castervoice/lib/ccr/python/python.py
  castervoice/lib/dfplus/merge/mergerule.py
  castervoice/lib/dfplus/state/actions.py
  castervoice/lib/dfplus/state/stack.py
  castervoice/lib/dfplus/state/stackitems.py
Labels: Refactor, Testing Required, [WIP]

#511 Make userspace rules work after changing profile
  _caster.py
Labels: Bug, Enhancement

#523 Corrected the reboot commands for Dragon and WRS
  castervoice/doc/CasterQuickReference.pdf
  castervoice/doc/CasterQuickReference.tex
Labels: Documentation

#514 Include two commands for right mouse down (lean) and up (hoist).
  CasterQuickReference.pdf
  castervoice/doc/CasterQuickReference.tex
  castervoice/lib/ccr/core/nav.py
  castervoice/lib/navigation.py
Labels: Enhancement

#524 Handle case when 'PROCESSOR_ARCHITEW6432' is not an environment var
  castervoice/lib/settings.py
Labels: Bug, Caster

#521 Change alt tab command `dredge` to go multiple windows back
  castervoice/lib/ccr/core/nav.py
Labels: Caster Core Spec, Enhancement, Waiting for User Reply

#346 Miscellaneous path configuration issues
  castervoice/asynch/settingswindow.py
  castervoice/lib/settings.py
Labels: Enhancement

#537 make some commands CCR in nav
  castervoice/lib/ccr/core/nav.py
Labels: Caster Core Spec, Enhancement

#493 add ContextAction for redo
  castervoice/lib/ccr/core/nav.py
Labels: Enhancement

#543 HTML workaround for Jetbrains IDE auto complete #541
  castervoice/lib/actions.py
  castervoice/lib/ccr/html/html.py
Labels: Bug, Caster Core Spec
