Repository dictation-toolbox/Caster, pull requests merged in 2019-06, with the labels that each got.

#553 Reimplement the action lines commands
  castervoice/apps/atom.py
  castervoice/apps/rstudio.py
  castervoice/apps/sublime.py
  castervoice/apps/vscode.py
  castervoice/doc/readthedocs/Application_Commands_Quick_Reference.md
  castervoice/lib/navigation.py
Labels: Enhancement, Grammar, HotFix, [WIP]

#490 Added Mock dependencies, Travis, Dragonfly text engine tests
  .pylintrc
  .travis.yml
  _caster.py
  castervoice/lib/clipboard.py
  castervoice/lib/ctrl/nexus.py
  castervoice/lib/dfplus/merge/mergerule.py
  castervoice/lib/settings.py
  castervoice/lib/tests/mocks.py
  castervoice/lib/tests/testrunner.py
  castervoice/lib/tests/unit/filter.py
  castervoice/lib/tests/unit/merger.py
  castervoice/lib/tests/unit/mergerule.py
  castervoice/lib/utilities.py
  requirements-dev.txt
  requirements.txt
  setup.py
Labels: New Feature

#573 Add default for mwith
  castervoice/apps/vscode.py
  castervoice/lib/dfplus/merge/ccrmerger.py
  castervoice/lib/dfplus/merge/mergerule.py
Labels: Caster Core Spec, Complete

#574 Load the same user profile after rebooting Dragon
  .pylintrc
  castervoice/bin/reboot.bat
  castervoice/lib/utilities.py
Labels: Caster Core Spec, Enhancement

#498 automate checking out pull request
  ReadMe.md
  castervoice/apps/chrome.py
  castervoice/apps/firefox.py
  castervoice/bin/share/git_repo_local_to_remote_match.toml.defaults
  castervoice/doc/readthedocs/Application_Commands_Quick_Reference.md
  castervoice/lib/github_automation.ahk
  castervoice/lib/github_automation.py
  castervoice/lib/settings.py
Labels: New Feature, [WIP]

#548 Punctuation refactor
  .gitignore
  castervoice/doc/CasterQuickReference.pdf
  castervoice/doc/CasterQuickReference.tex
  castervoice/lib/ccr/core/nav.py
  castervoice/lib/ccr/core/punctuation.py
Labels: Caster Core Spec, Refactor, [WIP]

#485 add text manipulation commands to nav
  castervoice/doc/readthedocs/Text_Manipulation.md
  castervoice/lib/ccr/__init__.py
  castervoice/lib/ccr/core/nav.py
  castervoice/lib/ccr/core/punctuation.py
  castervoice/lib/ccr/core/text_manipulation.py
  castervoice/lib/context.py
  castervoice/lib/navigation.py
  castervoice/lib/text_manipulation_functions.py
  mkdocs.yml
Labels: High Priority, [WIP]

#582 Revert clipboard to use json
  castervoice/lib/navigation.py
  castervoice/lib/settings.py
  castervoice/lib/utilities.py
Labels: Caster, High Priority

#586 Voice dev commands tweak
  castervoice/doc/readthedocs/CCR_languages_Quick_Reference.md
  castervoice/lib/ccr/voice_dev_commands/voice_dev_commands.py
Labels: Enhancement, Grammar, [WIP]

#571 add CCR rule to Chrome
  castervoice/apps/chrome.py
  castervoice/doc/readthedocs/Application_Commands_Quick_Reference.md
Labels: Enhancement, Grammar, Waiting for User Reply

#530 Refactor apps grammars to have standard grammar #520
  _caster.py
  castervoice/apps/__init__.py
  castervoice/apps/browser/__init__.py
  castervoice/apps/browser/browser.py
  castervoice/apps/browser/browser_shared_commands.py
  castervoice/apps/browser/chrome.py
  castervoice/apps/browser/firefox.py
  castervoice/apps/chrome.py
  castervoice/apps/firefox.py
  castervoice/apps/gitbash.py
  castervoice/apps/ide/__init__.py
  castervoice/apps/ide/ide.py
  castervoice/apps/ide/jetbrains.py
  castervoice/apps/jetbrains.py
  castervoice/apps/shared/__init__.py
  castervoice/apps/shared/directions.py
  castervoice/doc/readthedocs/Application_Commands_Quick_Reference.md
Labels: Community Feedback, New Feature

#559 add new commands to dragon.py
  castervoice/apps/dragon.py
Labels: Documentation Needed, Enhancement, Grammar

#501 Select text using douglas, rainbow, and legion
  castervoice/apps/griddouglas.py
  castervoice/apps/gridlegion.py
  castervoice/apps/gridrainbow.py
  castervoice/doc/readthedocs/Mouse.md
Labels: Documentation Needed, Enhancement

#588 add support for the 10 digits for text manipulation
  castervoice/doc/readthedocs/Text_Manipulation.md
  castervoice/lib/ccr/core/text_manipulation.py
  castervoice/lib/text_manipulation_functions.py
Labels: New Feature

#590 Add imports.py to reduce boilerplate
  castervoice/doc/readthedocs/Examples/Rule_Construction.md
  castervoice/lib/ccr/bash/bash.py
  castervoice/lib/ccr/core/alphabet.py
  castervoice/lib/ccr/core/nav.py
  castervoice/lib/ccr/core/numbers.py
  castervoice/lib/ccr/core/punctuation.py
  castervoice/lib/ccr/core/text_manipulation.py
  castervoice/lib/ccr/cpp/cpp.py
  castervoice/lib/ccr/csharp/csharp.py
  castervoice/lib/ccr/dart/dart.py
  castervoice/lib/ccr/go/go.py
  castervoice/lib/ccr/haxe/haxe.py
  castervoice/lib/ccr/html/html.py
  castervoice/lib/ccr/java/java.py
  castervoice/lib/ccr/javascript/javascript.py
  castervoice/lib/ccr/latex/latex.py
  castervoice/lib/ccr/markdown/markdown.py
  castervoice/lib/ccr/matlab/matlab.py
  castervoice/lib/ccr/prolog/prolog.py
  castervoice/lib/ccr/python/python.py
  castervoice/lib/ccr/r/r.py
  castervoice/lib/ccr/rust/rust.py
  castervoice/lib/ccr/sql/sql.py
  castervoice/lib/ccr/vhdl/vhdl.py
  castervoice/lib/ccr/voice_dev_commands/voice_dev_commands.py
  castervoice/lib/imports.py
Labels: Caster Core Spec, Documentation Needed, [WIP]

#599 Minimum version checking for dragonfly.
  _caster.py
Labels: Complete, Installation, New Feature

#596 Rule loading functions in control.py
  castervoice/lib/control.py
Labels: Documentation Needed, New Feature, [WIP]

#600 Documentation for new rule loading functions
  castervoice/doc/readthedocs/Examples/Rule_Construction.md
Labels: Documentation

#604 Major app rules clean up
  castervoice/apps/adobe_acrobat.py
  castervoice/apps/atom.py
  castervoice/apps/browser/chrome.py
  castervoice/apps/browser/firefox.py
  castervoice/apps/cmd.py
  castervoice/apps/dragon.py
  castervoice/apps/eclipse.py
  castervoice/apps/emacs.py
  castervoice/apps/excel.py
  castervoice/apps/explorer.py
  castervoice/apps/file_dialogue.py
  castervoice/apps/flashdevelop.py
  castervoice/apps/fman.py
  castervoice/apps/foxitreader.py
  castervoice/apps/gitbash.py
  castervoice/apps/githubdesktop.py
  castervoice/apps/gitter.py
  castervoice/apps/griddouglas.py
  castervoice/apps/gridlegion.py
  castervoice/apps/gridrainbow.py
  castervoice/apps/ide/jetbrains.py
  castervoice/apps/kdiff3.py
  castervoice/apps/lyx.py
  castervoice/apps/msvc.py
  castervoice/apps/notepadplusplus.py
  castervoice/apps/outlook.py
  castervoice/apps/rstudio.py
  castervoice/apps/sqldeveloper.py
  castervoice/apps/ssms.py
  castervoice/apps/sublime.py
  castervoice/apps/totalcmd.py
  castervoice/apps/typora.py
  castervoice/apps/visualstudio.py
  castervoice/apps/vscode.py
  castervoice/apps/winword.py
  castervoice/apps/wsr.py
  castervoice/lib/control.py
  castervoice/lib/imports.py
Labels: Bug, Grammar, Refactor

#606 Improve rule naming in rdescripts
  castervoice/lib/dfplus/merge/mergerule.py
Labels: Complete

#605 Further tidying of rule loading
  _caster.py
  castervoice/asynch/_hmc.py
  castervoice/asynch/sikuli/sikuli.py
  castervoice/lib/ccr/bash/bash.py
  castervoice/lib/ccr/core/alphabet.py
  castervoice/lib/ccr/core/nav.py
  castervoice/lib/ccr/core/numbers.py
  castervoice/lib/ccr/core/punctuation.py
  castervoice/lib/ccr/core/text_manipulation.py
  castervoice/lib/ccr/cpp/cpp.py
  castervoice/lib/ccr/csharp/csharp.py
  castervoice/lib/ccr/dart/dart.py
  castervoice/lib/ccr/go/go.py
  castervoice/lib/ccr/haxe/haxe.py
  castervoice/lib/ccr/html/html.py
  castervoice/lib/ccr/java/java.py
  castervoice/lib/ccr/javascript/javascript.py
  castervoice/lib/ccr/latex/latex.py
  castervoice/lib/ccr/markdown/markdown.py
  castervoice/lib/ccr/matlab/matlab.py
  castervoice/lib/ccr/prolog/prolog.py
  castervoice/lib/ccr/python/python.py
  castervoice/lib/ccr/r/r.py
  castervoice/lib/ccr/recording/again.py
  castervoice/lib/ccr/recording/alias.py
  castervoice/lib/ccr/recording/bringme.py
  castervoice/lib/ccr/rust/rust.py
  castervoice/lib/ccr/sql/sql.py
  castervoice/lib/ccr/vhdl/vhdl.py
  castervoice/lib/ccr/voice_dev_commands/voice_dev_commands.py
  castervoice/lib/imports.py
Labels: Refactor

#477 tweak a couple commands in VS code
  castervoice/apps/vscode.py
Labels: Enhancement

#577 Use Dragonfly's new timers and update Sikuli code
  castervoice/asynch/sikuli/sikuli.py
  castervoice/lib/ctrl/nexus.py
  castervoice/lib/ctrl/wsrdf.py
  castervoice/lib/dfplus/state/stackitems.py
  requirements-dev.txt
  requirements.txt
  setup.py
Labels: Caster, Enhancement, Sikulix

#607 Fixes the record from history "[times <n>]" command repeat macros
  castervoice/lib/ccr/recording/history.py
Labels: Bug

#475 fix Windows Explorer file dialogue navigation commands
  castervoice/apps/file_dialogue.py
Labels: Bug, Grammar

#608 Fixed Selfmodrule filter bug
  castervoice/lib/ccr/recording/alias.py
  castervoice/lib/ccr/recording/bringme.py
  castervoice/lib/control.py
Labels: Bug, Complete

#611 Fixed installtype function
  _caster.py
Labels: Bug

#613 App settings removed in settings.py
  castervoice/lib/settings.py
Labels: Caster, Complete, Removed
