Repository dictation-toolbox/Caster, pull requests merged in 2019-03, with the labels that each got.

#389 Post install Script for Setup.py
  post_setup.py
  setup.py
Labels: Complete, Enhancement, Installation, Needs Review

#397 Create dragonfly_dev_commands.py
  castervoice/lib/ccr/__init__.py
  castervoice/lib/ccr/core/punctuation.py
  castervoice/lib/ccr/dragonfly_dev_commands/__init__.py
  castervoice/lib/ccr/dragonfly_dev_commands/dragonfly_dev_commands.py
  castervoice262626/lib272727/ccr282828/dragonfly_dev_commands.py
Labels: Grammar, New Feature, [WIP]

#403 Implemented Typora application grammar
  castervoice/apps/typora.py
  castervoice/lib/settings.py
Labels: Documentation, Grammar, New Feature

#402 Bringme additions to make Caster more accessible by voice.
  castervoice/bin/share/bringme.toml.defaults
  castervoice/lib/ccr/recording/bringme.py
Labels: Community Feedback, Documentation, Enhancement, [WIP]

#407 Typora docs
  castervoice/doc/readthedocs/Application_Commands_Quick_Reference.md
Labels: Documentation, Grammar

#410 Add commands for GitHub desktop
  castervoice/apps/githubdesktop.py
  castervoice/doc/readthedocs/Application_Commands_Quick_Reference.md
  castervoice/lib/settings.py
Labels: Complete, Grammar

#411 fix dev choice command and made 'dev' required as a prefix to avoid m…
  castervoice/lib/ccr/dragonfly_dev_commands/dragonfly_dev_commands.py
Labels: Enhancement, Grammar

#409 add Microsoft Excel module
  castervoice/apps/excel.py
Labels: Grammar

#406 Create Outlook.py
  castervoice26/apps27/Outlook.py
Labels: Grammar

#412 Miscellaneous fixes
  _caster.py
  castervoice/apps/excel.py
  castervoice/apps/outlook.py
  castervoice/lib/ccr/__init__.py
  castervoice/lib/ccr/dev_commands/__init__.py
  castervoice/lib/ccr/dev_commands/dev_commands.py
  castervoice/lib/ccr/dragonfly_dev_commands/dragonfly_dev_commands.py
  castervoice/lib/settings.py
  castervoice26/apps27/Outlook.py
Labels: Complete, Grammar, HotFix

#413 Development command modification + documentation
  castervoice/doc/readthedocs/Application_Commands_Quick_Reference.md
  castervoice/doc/readthedocs/CCR_languages_Quick_Reference.md
  castervoice/lib/ccr/dev_commands/dev_commands.py
Labels: Documentation

#416 Verified and standardized rdescript on all applications.
  castervoice/apps/chrome.py
  castervoice/apps/excel.py
  castervoice/apps/firefox.py
  castervoice/apps/fman.py
  castervoice/apps/gridlegion.py
  castervoice/apps/gridrainbow.py
  castervoice/apps/kdiff3.py
  castervoice/apps/outlook.py
  castervoice/apps/ssms.py
  castervoice/apps/sublime.py
  castervoice/apps/totalcmd.py
Labels: Enhancement, Grammar

#415 Added to "Core:" rdescript for the core Caster ccr files.
  castervoice/lib/ccr/core/alphabet.py
  castervoice/lib/ccr/core/nav.py
  castervoice/lib/ccr/core/numbers.py
  castervoice/lib/ccr/core/punctuation.py
Labels: Caster Core Spec, Enhancement

#419 add new chrome commands
  castervoice/apps/chrome.py
Labels: Enhancement, Grammar

#420 Chrome documentation and cleanup
  castervoice/apps/chrome.py
  castervoice/doc/readthedocs/Application_Commands_Quick_Reference.md
Labels: Enhancement, Grammar

#421 Added rdescript to html.py
  castervoice/lib/ccr/html/html.py
Labels: Enhancement, Grammar

#423 Markdown CCR module
  castervoice/doc/readthedocs/CCR_languages_Quick_Reference.md
  castervoice/lib/ccr/__init__.py
  castervoice/lib/ccr/markdown/__init__.py
  castervoice/lib/ccr/markdown/markdown.py
Labels: Grammar, New Feature

#424 Add new Python language commands
  castervoice/lib/ccr/python/python.py
Labels: Enhancement, Grammar

#425 Post install Fix
  ReadMe.md
  castervoice/doc/Installation.md
  post_setup.py
  setup.py
Labels: High Priority, Installation, [WIP]

#428 Fix non-CCR for app rules
  castervoice/doc/readthedocs/CCR.md
  castervoice/lib/dfplus/merge/ccrmerger.py
Labels: Bug

#429 Tidy up phonetic alphabets
  castervoice/apps/excel.py
  castervoice/lib/alphanumeric.py
Labels: Refactor

#430 Post install enhancements with logging in new window during pip install
  post_setup.py
Labels: Installation, [WIP]

#427 Create an action wrapper for read_selected_without_altering_clipboard
  castervoice/apps/chrome.py
  castervoice/apps/rstudio.py
  castervoice/apps/sublime.py
  castervoice/doc/readthedocs/Application_Commands_Quick_Reference.md
  castervoice/lib/ccr/python/python.py
  castervoice/lib/context.py
  castervoice/lib/ctrl/nexus.py
  castervoice/lib/temporary.py
Labels: New Feature, Testing Required, [WIP]
