Repository dictation-toolbox/Caster, pull requests merged in 2019-12, with the labels that each got.

#443 Add Changelog
  .github_changelog_generator
  CHANGELOG.md
Labels: Documentation, Roadmap

#699 Clarify Aenea setup instructions
  docs/readthedocs/Aenea.md
Labels: Aenea, Installation

#700 [Trivial change] Docs CI are passing but ReadTheDocs badge fails
  docs/README.md
Labels: Bug, Documentation

#703 Travis update test runner path and utilize dragonfly test engine
  .travis.yml
  tests/testrunner.py
Labels: Tests, Travis-CI

#691 Add discussion of bug to text manipulation commands buglist
  docs/readthedocs/Text_Manipulation.md
Labels: Documentation

#708 Compiled `tirg-64.dll` for Legion MouseGrid
  castervoice/asynch/mouse/legion.py
  castervoice/lib/dll/tirg-32.dll
  castervoice/lib/dll/tirg-64.dll
Labels: MouseGrids

#710 Upon error in Status Window will come to the forefront.
  _caster.py
  castervoice/lib/settings.py
Labels: New Feature

#713 #712 Workaround - Renamed CCR dir with <name>_rules
  castervoice/rules/ccr/bash_rules/__init__.py
  castervoice/rules/ccr/bash_rules/bash.py
  castervoice/rules/ccr/cpp_rules/__init__.py
  castervoice/rules/ccr/cpp_rules/cpp.py
  castervoice/rules/ccr/csharp_rules/__init__.py
  castervoice/rules/ccr/csharp_rules/csharp.py
  castervoice/rules/ccr/dart_rules/__init__.py
  castervoice/rules/ccr/dart_rules/dart.py
  castervoice/rules/ccr/go_rules/__init__.py
  castervoice/rules/ccr/go_rules/go.py
  castervoice/rules/ccr/haxe_rules/__init__.py
  castervoice/rules/ccr/haxe_rules/haxe.py
  castervoice/rules/ccr/html_rules/__init__.py
  castervoice/rules/ccr/html_rules/html_rule.py
  castervoice/rules/ccr/java_rules/__init__.py
  castervoice/rules/ccr/java_rules/java.py
  castervoice/rules/ccr/java_rules/java2.py
  castervoice/rules/ccr/javascript_rules/__init__.py
  castervoice/rules/ccr/javascript_rules/javascript.py
  castervoice/rules/ccr/latex_rules/__init__.py
  castervoice/rules/ccr/latex_rules/latex.py
  castervoice/rules/ccr/markdown_rules/__init__.py
  castervoice/rules/ccr/markdown_rules/markdown.py
  castervoice/rules/ccr/matlab_rules/__init__.py
  castervoice/rules/ccr/matlab_rules/matlab.py
  castervoice/rules/ccr/matlab_rules/matlab2.py
  castervoice/rules/ccr/prolog_rules/__init__.py
  castervoice/rules/ccr/prolog_rules/prolog.py
  castervoice/rules/ccr/prolog_rules/prolog2.py
  castervoice/rules/ccr/python_rules/__init__.py
  castervoice/rules/ccr/python_rules/python.py
  castervoice/rules/ccr/python_rules/python2.py
  castervoice/rules/ccr/r_rules/__init__.py
  castervoice/rules/ccr/r_rules/r.py
  castervoice/rules/ccr/recording_rules/__init__.py
  castervoice/rules/ccr/recording_rules/again.py
  castervoice/rules/ccr/recording_rules/alias/__init__.py
  castervoice/rules/ccr/recording_rules/alias/base_alias.py
  castervoice/rules/ccr/recording_rules/alias/chain_alias.py
  castervoice/rules/ccr/recording_rules/alias/simple_alias.py
  castervoice/rules/ccr/recording_rules/bringme.py
  castervoice/rules/ccr/recording_rules/history.py
  castervoice/rules/ccr/rust_rules/__init__.py
  castervoice/rules/ccr/rust_rules/rust.py
  castervoice/rules/ccr/rust_rules/rust2.py
  castervoice/rules/ccr/sql_rules/__init__.py
  castervoice/rules/ccr/sql_rules/sql.py
  castervoice/rules/ccr/vhdl_rules/__init__.py
  castervoice/rules/ccr/vhdl_rules/vhdl.py
  castervoice/rules/ccr/vhdl_rules/vhdl2.py
  castervoice/rules/ccr/vhdl_rules/vhdl_support.py
  castervoice/rules/ccr/voice_dev_commands_rules/__init__.py
  castervoice/rules/ccr/voice_dev_commands_rules/voice_dev_commands.py
  tests/complexity.py
  tests/lib/ctrl/mgr/test_grammarManager.py
  tests/rules/ccr/test_rule_modules.py
Labels: 1.0.0 Rewrite

#709 move _set_rdescript to grammar manager
  castervoice/lib/ctrl/mgr/grammar_manager.py
  castervoice/lib/ctrl/mgr/rule_formatter.py
  castervoice/lib/merge/mergerule.py
  castervoice/lib/merge/selfmod/tree_rule/tree_rule.py
Labels: New Feature

#714 Added Microsoft Teams App Rule
  castervoice/rules/apps/chat/MSTeamsRule.py
Labels: Grammar, New Feature

#717 Fix missing repeats in the sublime edit up/down/next commands
  castervoice/rules/apps/editor/sublime.py
Labels: Bug, Grammar

#706 Fix AppContext for Aenea in Mapping Rule Maker
  castervoice/lib/contexts.py
  castervoice/lib/ctrl/mgr/rule_maker/mapping_rule_maker.py
  castervoice/lib/version.py
  castervoice/rules/apps/editor/atom.py
  castervoice/rules/apps/microsoft_office/outlook.py
  castervoice/rules/ccr/html_rules/html_rule.py
  castervoice/rules/ccr/recording_rules/bringme.py
  castervoice/rules/core/navigation_rules/nav.py
  castervoice/rules/core/text_manipulation_rules/text_manipulation_support.py
  docs/readthedocs/Aenea.md
Labels: 1.0.0 Rewrite, Aenea, Bug, Complete, Waiting For Issue/PR

#720 Added Sudoku grid
  castervoice/asynch/mouse/grids.py
  castervoice/lib/const.py
  castervoice/lib/navigation.py
  castervoice/lib/settings.py
  castervoice/rules/apps/mouse_grids/gridsudoku.py
  castervoice/rules/core/utility_rules/mouse_alts_rules.py
  docs/readthedocs/Mouse.md
Labels: MouseGrids, New Feature
