Repository dictation-toolbox/Caster, pull requests merged in 2019-08, with the labels that each got.

#668 add longhand punctuation names
  castervoice/lib/ccr/core/nav.py
Labels: Caster Core Spec

#671 Allow Unicode characters in history
  castervoice/asynch/hmc/hmc_recording.py
  castervoice/lib/ccr/recording/history.py
Labels: Bug, GUI

#673 Sets user directory with Permissions check with fallback location
  castervoice/lib/settings.py
Labels: Bug

#674 Find pip cross platform without environment variable
  _caster.py
  castervoice/lib/ctrl/dependencies.py
Labels: Bug

#665 Added Clipboard read\write retry attempts on failure
  castervoice/lib/context.py
Labels: Bug, Caster, Testing Required

#675 # Switch mouse commands to use standard cancel phrase
  castervoice/apps/griddouglas.py
  castervoice/apps/gridlegion.py
  castervoice/apps/gridrainbow.py
  castervoice/lib/ccr/standard.py
Labels: Caster Core Spec, GUI

#681 Remove settings as a hard dependency for Dependency.py
  _caster.py
  castervoice/lib/ctrl/dependencies.py
  castervoice/lib/ctrl/nexus.py
  castervoice/lib/navigation.py
  setup.py
Labels: Refactor

#676 Implements tomlkit in place of toml dependency
  castervoice/lib/dfplus/merge/ccrmerger.py
  castervoice/lib/github_automation.py
  castervoice/lib/settings.py
  castervoice/lib/utilities.py
  requirements-dev.txt
  requirements.txt
  setup.py
Labels: Bug, Complete, Enhancement

#682 remove unneeded itertools import (trivial)
  castervoice/lib/text_manipulation_functions.py
Labels: Grammar, Removal

#683 Workspace fix for 1903 + kaldi compatibility
  _caster.py
  castervoice/bin/VirtualDesktopAccessor.dll
  castervoice/bin/VirtualDesktopAccessor32.dll
  castervoice/bin/VirtualDesktopAccessor64.dll
  castervoice/lib/ccr/core/nav.py
  castervoice/lib/utilities.py
Labels: Bug, Refactor

#664 Lexicon Optimizations
  _caster.py
  castervoice/apps/atom.py
  castervoice/apps/browser/browser.py
  castervoice/apps/gitbash.py
  castervoice/apps/gitter.py
  castervoice/apps/ide/ide.py
  castervoice/apps/msvc.py
  castervoice/apps/ssms.py
  castervoice/apps/sublime.py
  castervoice/apps/visualstudio.py
  castervoice/apps/vscode.py
  castervoice/lib/ccr/core/nav.py
  castervoice/lib/ccr/html/html.py
  castervoice/lib/ccr/java/java.py
  castervoice/lib/ccr/latex/latex.py
  castervoice/lib/ccr/markdown/markdown.py
  castervoice/lib/ccr/python/python.py
  castervoice/lib/ccr/rust/rust.py
  docs/CasterQuickReference.tex
  docs/readthedocs/Application_Commands_Quick_Reference.md
  docs/readthedocs/CCR_languages_Quick_Reference.md
Labels: Caster, Refactor
