Repository dictation-toolbox/Caster, pull requests merged in 2019-01, with the labels that each got.

#368 Text formatting bug fixes
  caster/lib/navigation.py
Labels: Bug

#370 Text normalization bug fix
  caster/lib/textformat.py
Labels: Bug, Community Feedback

#366 Add basic LyX functionality
  caster/apps/lyx.py
  caster/lib/settings.py
Labels: Grammar

#363 Automatically focus on the address bar when adding bring me's
  caster/lib/ccr/recording/bringme.py
Labels: Enhancement

#352 Switching AppContext Key and Text libraries
  caster/apps/cmd.py
  caster/apps/explorer.py
  caster/apps/gitbash.py
  caster/apps/griddouglas.py
  caster/apps/gridlegion.py
  caster/apps/gridrainbow.py
  caster/apps/totalcmd.py
  caster/apps/visualstudio.py
  caster/asynch/_hmc.py
  caster/lib/context.py
  caster/lib/tests/unit/mergerule.py
Labels: Enhancement

#373 Alias updates
  _caster.py
  caster/lib/ccr/recording/alias.py
  caster/lib/dfplus/merge/selfmodrule.py
Labels: Enhancement
