Repository dictation-toolbox/Caster, pull requests merged in 2020-01, with the labels that each got.

#718 Caster settings.py rework
  castervoice/asynch/mouse/legion.py
  castervoice/lib/ctrl/dependencies.py
  castervoice/lib/merge/selfmod/tree_rule/tree_rule.py
  castervoice/lib/settings.py
  castervoice/lib/util/pathlib/__init__.py
  castervoice/lib/utilities.py
  castervoice/lib/version.py
  castervoice/rules/ccr/recording_rules/bringme.py
  docs/README.md
  docs/readthedocs/Aenea.md
  docs/readthedocs/CCR.md
  docs/readthedocs/Sikuli.md
  requirements-dev.txt
  requirements.txt
  setup.py
Labels: Bug, Documentation Needed, New Feature, Refactor

#725 Pr settings window bandaid
  castervoice/asynch/settingswindow.py
Labels: BugFix, Complete, GUI

#727 Define default Caster `hooks` in settings.
  castervoice/lib/merge/ccrmerging2/hooks/hooks_runner.py
  castervoice/lib/settings.py
  castervoice/lib/version.py
Labels: 1.0.0 Rewrite, New Feature

#728 Fix MouseGrid out of focus
  castervoice/lib/utilities.py
  castervoice/rules/core/utility_rules/mouse_alts_rules.py
Labels: BugFix, MouseGrids

#731 Initialized update_check after settings
  _caster.py
  castervoice/lib/ctrl/dependencies.py
  castervoice/lib/ctrl/updatecheck.py
  castervoice/rules/core/utility_rules/caster_rule.py
Labels: BugFix, [WIP]

#730 Bug fix: multi-clipboard wasn't initialized.
  .gitignore
  castervoice/lib/navigation.py
  tests/test_util/utilities_mocking.py
  tests/testrunner.py
Labels: BugFix, Caster
