Repository dictation-toolbox/Caster, pull requests merged in 2020-05, with the labels that each got.

#805 Add command to open line above
  castervoice/lib/navigation.py
  castervoice/rules/core/navigation_rules/nav.py
Labels: Caster Core Spec

#811 Remove Playback from legion mouse click
  castervoice/rules/apps/mouse_grids/gridlegion.py
Labels: Enhancement, Kaldi, Windows Speech Recognition

#806 content_request_generator handles special characters UTF-8 py3
  castervoice/lib/ctrl/mgr/loading/load/content_request_generator.py
Labels: Bug, Python 3

#813 Two minor tweaks for vscode grammar (should be trivial)
  castervoice/rules/apps/editor/vscode_rules/vscode.py
  docs/readthedocs/Caster_Commands/Application_Commands_Quick_Reference.md
Labels: Enhancement, Grammar

#790 Add Unity3D grammar
  castervoice/rules/apps/editor/unity.py
  docs/readthedocs/Caster_Commands/Application_Commands_Quick_Reference.md
Labels: Grammar, New Feature, WIP

#802 New command to scroll mouse wheel continuously
  castervoice/rules/core/navigation_rules/nav2.py
  docs/readthedocs/Caster_Commands/Mouse.md
Labels: Caster Core Spec, New Feature

#818 vscode grammar update
  castervoice/rules/apps/editor/vscode_rules/vscode2.py
  docs/readthedocs/Caster_Commands/Application_Commands_Quick_Reference.md
Labels: BugFix, Complete, Enhancement, Grammar

#819 added CSS commands
  castervoice/rules/ccr/css_rules/__init__.py
  castervoice/rules/ccr/css_rules/css.py
  docs/readthedocs/Caster_Commands/CCR_languages_Quick_Reference.md
Labels: Grammar, New Feature

#820 Fix dragonfly `FuncContext` Caster App integration
  castervoice/lib/ctrl/mgr/rule_maker/mapping_rule_maker.py
  castervoice/lib/merge/ccrmerging2/ccrmerger2.py
Labels: BugFix, Caster

#815 Added change engine mic state and mode on caster startup for DNS
  _caster.py
  castervoice/lib/ctrl/configure_engine.py
  castervoice/lib/ctrl/mgr/engine_manager.py
  castervoice/lib/ctrl/nexus.py
  castervoice/lib/settings.py
  castervoice/rules/core/engine_manager_rules/__init__.py
  docs/readthedocs/Caster_Settings/settings.md
  tests/lib/ctrl/test_EngineModesManager.py
Labels: Caster Core Spec, Complete, Dragon Naturally Speaking, New Feature
