Repository dictation-toolbox/Caster, pull requests merged in 2020-09, with the labels that each got.

#845 Update Kaldi.md
  docs/readthedocs/Installation/Kaldi.md
Labels: Documentation

#847 Add new shortcuts for Visual Studio
  castervoice/rules/apps/editor/visualstudio.py
  docs/readthedocs/Caster_Commands/Application_Commands_Quick_Reference.md
  docs/readthedocs/Caster_Commands/CCR_languages_Quick_Reference.md
Labels: Enhancement, Grammar

#848 Jetbrains Commands Updates
  castervoice/rules/apps/editor/jetbrains.py
  docs/readthedocs/Caster_Commands/Application_Commands_Quick_Reference.md
Labels: Enhancement, Grammar

#851 Add contexts for cross platform
  castervoice/lib/contexts.py
Labels: Caster, New Feature
