Repository dictation-toolbox/Caster, pull requests merged in 2020-04, with the labels that each got.

#779 [Trivial change] Fix broken sample.py command
  docs/readthedocs/Rule_Construction/Dragonfly_Rules/Sample_File.md
  sample.py
Labels: Bug, Documentation

#780 Standardising function keys
  castervoice/rules/core/navigation_rules/nav.py
  castervoice/rules/core/navigation_rules/nav2.py
Labels: Caster Core Spec, Enhancement

#783 Trivial change: Fixed discord link and log.txt bringme path
  castervoice/rules/ccr/recording_rules/bringme.py
Labels: BugFix

#784 Trivial change: Fix broken link on 'Using Voice Commands' Docs
  docs/readthedocs/Caster_Commands/Using_Voice_Commands.md
Labels: Documentation

#785 Convert bringme feature to non ccr
  castervoice/rules/ccr/recording_rules/bringme.py
Labels: Enhancement

#787 Trivial Change: fix alias link
  docs/README.md
Labels: Documentation

#791 Trivial change: Fix vscode previous pane goes left
  castervoice/rules/apps/editor/vscode_rules/vscode2.py
Labels: BugFix, Grammar

#792 Clarified Caster vs Natlink User directory docs
  docs/readthedocs/User_Dir/Caster_User_Dir.md
Labels: Documentation

#796 Alter reboot command Kaldi
  castervoice/lib/utilities.py
Labels: BugFix, Caster Core Spec

#788 downscale legion
  castervoice/asynch/mouse/legion.py
  castervoice/lib/navigation.py
  castervoice/lib/settings.py
  castervoice/rules/core/utility_rules/mouse_alts_rules.py
  docs/readthedocs/Caster_Commands/Mouse.md
Labels: Enhancement, GUI, MouseGrids

#801 Fix `enable ccr` for dragon vocabulary
  castervoice/rules/core/utility_rules/caster_rule.py
Labels: Caster Core Spec

#803 Trivial change: Four new Rust syntax commands
  castervoice/rules/ccr/rust_rules/rust.py
Labels: Enhancement, Grammar
