Repository dictation-toolbox/Caster, pull requests merged in 2020-07, with the labels that each got.

#828 Add active python/pip info in install scripts
  Install_Caster_DNS-WSR.bat
  Install_Caster_Kaldi.bat
Labels: Enhancement, Installation

#823 Sanitize BringMe/Alias specs
  castervoice/rules/ccr/recording_rules/alias/base_alias.py
  castervoice/rules/ccr/recording_rules/bringme.py
Labels: BugFix, Complete

#829 Rename the window manipulation maximize and minimize commands to include `win`
  CasterQuickReference.pdf
  castervoice/rules/core/navigation_rules/window_mgmt_rule.py
  docs/CasterQuickReference.pdf
  docs/CasterQuickReference.tex
Labels: Caster Core Spec, Enhancement

#835 BugFix: `Again` grammar #833 and #834
  castervoice/rules/ccr/recording_rules/again.py
Labels: BugFix, Caster Core Spec

#836 Add additional sublime shortcuts
  castervoice/lib/navigation.py
  castervoice/rules/apps/editor/sublime.py
  docs/readthedocs/Caster_Commands/Application_Commands_Quick_Reference.md
Labels: Grammar
