Repository dictation-toolbox/Caster, pull requests merged in 2020-03, with the labels that each got.

#754 Migrate Settings Window implementation from Wx to Qt
  castervoice/asynch/settingswindow.py
  castervoice/asynch/settingswindow_qt.py
  castervoice/asynch/settingswindow_wx.py
Labels: GUI

#762 Fix settings window crash on complete command on Windows
  castervoice/asynch/hmc/homunculus.py
  castervoice/asynch/mouse/grids.py
  castervoice/asynch/settingswindow_qt.py
  castervoice/asynch/settingswindow_wx.py
  castervoice/asynch/sikuli/server/xmlrpc_server.sikuli/xmlrpc_server.py
Labels: BugFix, GUI, Python 3

#760 Use Popen.wait to wait for mouse grid subprocess to exit
  castervoice/asynch/mouse/grids.py
  castervoice/lib/ctrl/nexus.py
  castervoice/lib/ctrl/updatecheck.py
  castervoice/lib/merge/mergerule.py
  castervoice/lib/merge/state/stackitems.py
  castervoice/lib/navigation.py
  castervoice/rules/apps/mouse_grids/griddouglas.py
  castervoice/rules/apps/mouse_grids/gridlegion.py
  castervoice/rules/apps/mouse_grids/gridrainbow.py
  castervoice/rules/apps/mouse_grids/gridsudoku.py
  castervoice/rules/core/alphabet_rules/alphabet.py
  requirements-dev.txt
  requirements.txt
Labels: Enhancement, MouseGrids

#763 Add Dragonfly FuncContext support
  castervoice/lib/ctrl/mgr/rule_details.py
  castervoice/lib/ctrl/mgr/rule_maker/mapping_rule_maker.py
  castervoice/lib/ctrl/mgr/validation/details/function_context_validator.py
  castervoice/lib/merge/ccrmerging2/ccrmerger2.py
Labels: Caster, New Feature

#764 Initial macOS support
  .travis.yml
  castervoice/lib/const.py
  castervoice/lib/ctrl/dependencies.py
  castervoice/lib/dev/dev.py
  castervoice/lib/navigation.py
  castervoice/lib/settings.py
  castervoice/lib/utilities.py
  castervoice/lib/virtual_desktops.py
  castervoice/lib/windows_virtual_desktops.py
  castervoice/rules/ccr/recording_rules/bringme.py
  castervoice/rules/core/navigation_rules/window_mgmt_rule.py
  requirements-mac.txt
  setup.py
Labels: Mac OS, New Feature

#768 VScode: "go back" default to 1
  castervoice/rules/apps/editor/vscode_rules/vscode2.py
  docs/readthedocs/Caster_Commands/Application_Commands_Quick_Reference.md
Labels: BugFix, Grammar

#766 Move tab left/right in VsCode
  castervoice/rules/apps/editor/vscode_rules/vscode2.py
Labels: Documentation Needed, Grammar, New Feature

#767 Trivial Change: Add missing back tab command in chrome
  castervoice/rules/apps/browser/chrome.py
  castervoice/rules/apps/browser/firefox.py
Labels: Grammar

#771 Add Webex Teams Rule
  castervoice/rules/apps/chat/webexteams.py
  docs/readthedocs/Caster_Commands/Application_Commands_Quick_Reference.md
  tests/rules/apps/test_rule_modules.py
Labels: Grammar, New Feature

#777 Trivial change: Expand function key range to include F10-F12
  castervoice/rules/core/navigation_rules/nav.py
Labels: Enhancement
