Repository dictation-toolbox/Caster, pull requests merged in 2021-06, with the labels that each got.

#896 Remove function keys from nav2
  castervoice/rules/core/navigation_rules/nav2.py
Labels: Caster Core Spec

#893 Prevent multiple navigation overlays from stacking
  castervoice/lib/navigation.py
Labels: Enhancement, MouseGrids

#899 Implement function context for mouse grids
  castervoice/lib/navigation.py
  castervoice/lib/utilities.py
  castervoice/rules/apps/mouse_grids/griddouglas.py
  castervoice/rules/apps/mouse_grids/gridlegion.py
  castervoice/rules/apps/mouse_grids/gridrainbow.py
  castervoice/rules/apps/mouse_grids/gridsudoku.py
  castervoice/rules/core/utility_rules/mouse_alts_rules.py
Labels: MouseGrids

#900 Simplify LegionGrid screen capture
  castervoice/asynch/mouse/legion.py
  castervoice/lib/gdi.py
Labels: Enhancement, MouseGrids

#897 Enhanced grids linux + complete Sudoku
  castervoice/asynch/mouse/grids.py
  castervoice/lib/settings.py
  castervoice/rules/apps/mouse_grids/griddouglas.py
  castervoice/rules/apps/mouse_grids/gridlegion.py
  castervoice/rules/apps/mouse_grids/gridrainbow.py
  castervoice/rules/apps/mouse_grids/gridsudoku.py
  requirements-dev.txt
  requirements-mac-linux.txt
Labels: Enhancement, Linux OS, MouseGrids
